<<<<<<< HEAD
agentsfolderpath: /home/user/projekte/PIA/P.I.A_3.0-public_version/PIA/Agents
=======
agentsfolderpath: /home/emil/projekte/PIA/P.I.A_3.0-public_version/PIA/Agents
voskmodel:/home/emil/Downloads/vosk-model-de-0.21
>>>>>>> 151a47c (Enhances configuration with Vosk model path)
